### ISSUE TITLE
Todo for Self-Hosting JPRQ

### ISSUE THREAD

**Issue by hoosnick** [old-juniors/qltrq#1]
- [ ] domain (http://qltrq.uz)
- [ ] website (https://qltrq.old-juniors.uz)
- [ ] cli + github action release binaries
- [ ] server + wildcard + ssl, dns-01, ...
- [ ] implementation of "allowed users"
